
name: image_compressor_admob
description: A Flutter image compressor app with AdMob integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  flutter_image_compress: ^2.0.4
  share_plus: ^7.0.2
  url_launcher: ^6.2.4
  toggle_switch: ^2.1.0  
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
